"""
Jupyter Notebook Metadata Cleaner for GitHub
--------------------------------------------
This script automatically searches the directory where it is located for all 
Jupyter Notebook (.ipynb) files. It removes 'widgets' metadata (often 
generated by tqdm or Colab progress bars) that causes GitHub 
to display an 'Invalid Notebook' error instead of rendering the file.
"""

import nbformat
import os

def clean_all_notebooks_in_dir():
    # Get the directory where THIS script is saved
    script_dir = os.path.dirname(os.path.abspath(__file__))
    
    # List all files in the directory
    files = os.listdir(script_dir)
    
    # Filter for notebook files
    notebook_files = [f for f in files if f.endswith('.ipynb')]
    
    if not notebook_files:
        print(f"No notebook files found in: {script_dir}")
        return

    for file_name in notebook_files:
        file_path = os.path.join(script_dir, file_name)
        
        try:
            # Read the notebook
            with open(file_path, 'r', encoding='utf-8') as f:
                nb = nbformat.read(f, as_version=4)
            
            # Remove the problematic widgets metadata
            if 'widgets' in nb.metadata:
                del nb.metadata['widgets']
                print(f"Successfully cleaned widgets from: {file_name}")
                
                # Write the cleaned notebook back
                with open(file_path, 'w', encoding='utf-8') as f:
                    nbformat.write(nb, f)
            else:
                print(f"Skipped {file_name}: No widgets found.")
                
        except Exception as e:
            print(f"Error processing {file_name}: {e}")

if __name__ == "__main__":
    clean_all_notebooks_in_dir()